// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	entities "github.com/xurceo/plain-tcms/entities"
)

// DefectRepository is an autogenerated mock type for the DefectRepository type
type DefectRepository struct {
	mock.Mock
}

// DeleteDefect provides a mock function with given fields: id
func (_m *DefectRepository) DeleteDefect(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteDefect")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetDefectByID provides a mock function with given fields: id
func (_m *DefectRepository) GetDefectByID(id string) (entities.Defect, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetDefectByID")
	}

	var r0 entities.Defect
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (entities.Defect, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) entities.Defect); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(entities.Defect)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateDefect provides a mock function with given fields: id, req
func (_m *DefectRepository) UpdateDefect(id string, req entities.CreateDefectRequest) (entities.Defect, error) {
	ret := _m.Called(id, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDefect")
	}

	var r0 entities.Defect
	var r1 error
	if rf, ok := ret.Get(0).(func(string, entities.CreateDefectRequest) (entities.Defect, error)); ok {
		return rf(id, req)
	}
	if rf, ok := ret.Get(0).(func(string, entities.CreateDefectRequest) entities.Defect); ok {
		r0 = rf(id, req)
	} else {
		r0 = ret.Get(0).(entities.Defect)
	}

	if rf, ok := ret.Get(1).(func(string, entities.CreateDefectRequest) error); ok {
		r1 = rf(id, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewDefectRepository creates a new instance of DefectRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDefectRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *DefectRepository {
	mock := &DefectRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
