// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	entities "github.com/xurceo/plain-tcms/entities"
)

// OrganizationRepository is an autogenerated mock type for the OrganizationRepository type
type OrganizationRepository struct {
	mock.Mock
}

// AddMember provides a mock function with given fields: orgID, req
func (_m *OrganizationRepository) AddMember(orgID string, req entities.CreateOrganizationMemberRequest) (entities.OrganizationMember, error) {
	ret := _m.Called(orgID, req)

	if len(ret) == 0 {
		panic("no return value specified for AddMember")
	}

	var r0 entities.OrganizationMember
	var r1 error
	if rf, ok := ret.Get(0).(func(string, entities.CreateOrganizationMemberRequest) (entities.OrganizationMember, error)); ok {
		return rf(orgID, req)
	}
	if rf, ok := ret.Get(0).(func(string, entities.CreateOrganizationMemberRequest) entities.OrganizationMember); ok {
		r0 = rf(orgID, req)
	} else {
		r0 = ret.Get(0).(entities.OrganizationMember)
	}

	if rf, ok := ret.Get(1).(func(string, entities.CreateOrganizationMemberRequest) error); ok {
		r1 = rf(orgID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateOrganization provides a mock function with given fields: req
func (_m *OrganizationRepository) CreateOrganization(req entities.CreateOrganizationRequest) (entities.Organization, error) {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrganization")
	}

	var r0 entities.Organization
	var r1 error
	if rf, ok := ret.Get(0).(func(entities.CreateOrganizationRequest) (entities.Organization, error)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(entities.CreateOrganizationRequest) entities.Organization); ok {
		r0 = rf(req)
	} else {
		r0 = ret.Get(0).(entities.Organization)
	}

	if rf, ok := ret.Get(1).(func(entities.CreateOrganizationRequest) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteOrganization provides a mock function with given fields: id
func (_m *OrganizationRepository) DeleteOrganization(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteOrganization")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAllOrganizations provides a mock function with no fields
func (_m *OrganizationRepository) GetAllOrganizations() ([]entities.Organization, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllOrganizations")
	}

	var r0 []entities.Organization
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]entities.Organization, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []entities.Organization); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.Organization)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetMembers provides a mock function with given fields: orgID
func (_m *OrganizationRepository) GetMembers(orgID string) ([]entities.OrganizationMember, error) {
	ret := _m.Called(orgID)

	if len(ret) == 0 {
		panic("no return value specified for GetMembers")
	}

	var r0 []entities.OrganizationMember
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]entities.OrganizationMember, error)); ok {
		return rf(orgID)
	}
	if rf, ok := ret.Get(0).(func(string) []entities.OrganizationMember); ok {
		r0 = rf(orgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.OrganizationMember)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(orgID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOrganizationByID provides a mock function with given fields: id
func (_m *OrganizationRepository) GetOrganizationByID(id string) (entities.Organization, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetOrganizationByID")
	}

	var r0 entities.Organization
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (entities.Organization, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) entities.Organization); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(entities.Organization)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RemoveMember provides a mock function with given fields: orgID, userID
func (_m *OrganizationRepository) RemoveMember(orgID string, userID string) error {
	ret := _m.Called(orgID, userID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveMember")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(orgID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewOrganizationRepository creates a new instance of OrganizationRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrganizationRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrganizationRepository {
	mock := &OrganizationRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
