// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	entities "github.com/xurceo/plain-tcms/entities"
)

// ProjectRepository is an autogenerated mock type for the ProjectRepository type
type ProjectRepository struct {
	mock.Mock
}

// CreateProject provides a mock function with given fields: req
func (_m *ProjectRepository) CreateProject(req entities.CreateProjectRequest) (entities.Project, error) {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for CreateProject")
	}

	var r0 entities.Project
	var r1 error
	if rf, ok := ret.Get(0).(func(entities.CreateProjectRequest) (entities.Project, error)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(entities.CreateProjectRequest) entities.Project); ok {
		r0 = rf(req)
	} else {
		r0 = ret.Get(0).(entities.Project)
	}

	if rf, ok := ret.Get(1).(func(entities.CreateProjectRequest) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteProject provides a mock function with given fields: id
func (_m *ProjectRepository) DeleteProject(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteProject")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAllProjects provides a mock function with no fields
func (_m *ProjectRepository) GetAllProjects() ([]entities.Project, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllProjects")
	}

	var r0 []entities.Project
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]entities.Project, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []entities.Project); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.Project)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetProjectByID provides a mock function with given fields: id
func (_m *ProjectRepository) GetProjectByID(id string) (entities.Project, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetProjectByID")
	}

	var r0 entities.Project
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (entities.Project, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) entities.Project); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(entities.Project)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetProjectsByOrgID provides a mock function with given fields: orgID
func (_m *ProjectRepository) GetProjectsByOrgID(orgID string) ([]entities.Project, error) {
	ret := _m.Called(orgID)

	if len(ret) == 0 {
		panic("no return value specified for GetProjectsByOrgID")
	}

	var r0 []entities.Project
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]entities.Project, error)); ok {
		return rf(orgID)
	}
	if rf, ok := ret.Get(0).(func(string) []entities.Project); ok {
		r0 = rf(orgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.Project)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(orgID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateProject provides a mock function with given fields: id, req
func (_m *ProjectRepository) UpdateProject(id string, req entities.CreateProjectRequest) (entities.Project, error) {
	ret := _m.Called(id, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProject")
	}

	var r0 entities.Project
	var r1 error
	if rf, ok := ret.Get(0).(func(string, entities.CreateProjectRequest) (entities.Project, error)); ok {
		return rf(id, req)
	}
	if rf, ok := ret.Get(0).(func(string, entities.CreateProjectRequest) entities.Project); ok {
		r0 = rf(id, req)
	} else {
		r0 = ret.Get(0).(entities.Project)
	}

	if rf, ok := ret.Get(1).(func(string, entities.CreateProjectRequest) error); ok {
		r1 = rf(id, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewProjectRepository creates a new instance of ProjectRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProjectRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProjectRepository {
	mock := &ProjectRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
