// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	entities "github.com/xurceo/plain-tcms/entities"
)

// TestSuiteRepository is an autogenerated mock type for the TestSuiteRepository type
type TestSuiteRepository struct {
	mock.Mock
}

// CreateTestSuite provides a mock function with given fields: projectID, req
func (_m *TestSuiteRepository) CreateTestSuite(projectID string, req entities.CreateTestSuiteRequest) (entities.TestSuite, error) {
	ret := _m.Called(projectID, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateTestSuite")
	}

	var r0 entities.TestSuite
	var r1 error
	if rf, ok := ret.Get(0).(func(string, entities.CreateTestSuiteRequest) (entities.TestSuite, error)); ok {
		return rf(projectID, req)
	}
	if rf, ok := ret.Get(0).(func(string, entities.CreateTestSuiteRequest) entities.TestSuite); ok {
		r0 = rf(projectID, req)
	} else {
		r0 = ret.Get(0).(entities.TestSuite)
	}

	if rf, ok := ret.Get(1).(func(string, entities.CreateTestSuiteRequest) error); ok {
		r1 = rf(projectID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteTestSuite provides a mock function with given fields: id
func (_m *TestSuiteRepository) DeleteTestSuite(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTestSuite")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetTestSuiteByID provides a mock function with given fields: id
func (_m *TestSuiteRepository) GetTestSuiteByID(id string) (entities.TestSuite, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetTestSuiteByID")
	}

	var r0 entities.TestSuite
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (entities.TestSuite, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) entities.TestSuite); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(entities.TestSuite)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTestSuitesByProject provides a mock function with given fields: projectID
func (_m *TestSuiteRepository) GetTestSuitesByProject(projectID string) ([]entities.TestSuite, error) {
	ret := _m.Called(projectID)

	if len(ret) == 0 {
		panic("no return value specified for GetTestSuitesByProject")
	}

	var r0 []entities.TestSuite
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]entities.TestSuite, error)); ok {
		return rf(projectID)
	}
	if rf, ok := ret.Get(0).(func(string) []entities.TestSuite); ok {
		r0 = rf(projectID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.TestSuite)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(projectID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateTestSuite provides a mock function with given fields: id, req
func (_m *TestSuiteRepository) UpdateTestSuite(id string, req entities.CreateTestSuiteRequest) (entities.TestSuite, error) {
	ret := _m.Called(id, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTestSuite")
	}

	var r0 entities.TestSuite
	var r1 error
	if rf, ok := ret.Get(0).(func(string, entities.CreateTestSuiteRequest) (entities.TestSuite, error)); ok {
		return rf(id, req)
	}
	if rf, ok := ret.Get(0).(func(string, entities.CreateTestSuiteRequest) entities.TestSuite); ok {
		r0 = rf(id, req)
	} else {
		r0 = ret.Get(0).(entities.TestSuite)
	}

	if rf, ok := ret.Get(1).(func(string, entities.CreateTestSuiteRequest) error); ok {
		r1 = rf(id, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTestSuiteRepository creates a new instance of TestSuiteRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTestSuiteRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *TestSuiteRepository {
	mock := &TestSuiteRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
