// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	entities "github.com/xurceo/plain-tcms/entities"
)

// TestResultRepository is an autogenerated mock type for the TestResultRepository type
type TestResultRepository struct {
	mock.Mock
}

// AddAttachmentToResult provides a mock function with given fields: resultID, req
func (_m *TestResultRepository) AddAttachmentToResult(resultID string, req entities.CreateResultAttachmentRequest) (entities.ResultAttachment, error) {
	ret := _m.Called(resultID, req)

	if len(ret) == 0 {
		panic("no return value specified for AddAttachmentToResult")
	}

	var r0 entities.ResultAttachment
	var r1 error
	if rf, ok := ret.Get(0).(func(string, entities.CreateResultAttachmentRequest) (entities.ResultAttachment, error)); ok {
		return rf(resultID, req)
	}
	if rf, ok := ret.Get(0).(func(string, entities.CreateResultAttachmentRequest) entities.ResultAttachment); ok {
		r0 = rf(resultID, req)
	} else {
		r0 = ret.Get(0).(entities.ResultAttachment)
	}

	if rf, ok := ret.Get(1).(func(string, entities.CreateResultAttachmentRequest) error); ok {
		r1 = rf(resultID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAttachmentsByResult provides a mock function with given fields: resultID
func (_m *TestResultRepository) GetAttachmentsByResult(resultID string) ([]entities.ResultAttachment, error) {
	ret := _m.Called(resultID)

	if len(ret) == 0 {
		panic("no return value specified for GetAttachmentsByResult")
	}

	var r0 []entities.ResultAttachment
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]entities.ResultAttachment, error)); ok {
		return rf(resultID)
	}
	if rf, ok := ret.Get(0).(func(string) []entities.ResultAttachment); ok {
		r0 = rf(resultID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.ResultAttachment)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(resultID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTestResultByID provides a mock function with given fields: id
func (_m *TestResultRepository) GetTestResultByID(id string) (entities.TestResult, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetTestResultByID")
	}

	var r0 entities.TestResult
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (entities.TestResult, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) entities.TestResult); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(entities.TestResult)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateTestResult provides a mock function with given fields: id, req
func (_m *TestResultRepository) UpdateTestResult(id string, req entities.CreateTestResultRequest) (entities.TestResult, error) {
	ret := _m.Called(id, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTestResult")
	}

	var r0 entities.TestResult
	var r1 error
	if rf, ok := ret.Get(0).(func(string, entities.CreateTestResultRequest) (entities.TestResult, error)); ok {
		return rf(id, req)
	}
	if rf, ok := ret.Get(0).(func(string, entities.CreateTestResultRequest) entities.TestResult); ok {
		r0 = rf(id, req)
	} else {
		r0 = ret.Get(0).(entities.TestResult)
	}

	if rf, ok := ret.Get(1).(func(string, entities.CreateTestResultRequest) error); ok {
		r1 = rf(id, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTestResultRepository creates a new instance of TestResultRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTestResultRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *TestResultRepository {
	mock := &TestResultRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
