// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	entities "github.com/xurceo/plain-tcms/entities"
)

// TestPlanRepository is an autogenerated mock type for the TestPlanRepository type
type TestPlanRepository struct {
	mock.Mock
}

// CreateTestPlan provides a mock function with given fields: projectID, req
func (_m *TestPlanRepository) CreateTestPlan(projectID string, req entities.CreateTestPlanRequest) (entities.TestPlan, error) {
	ret := _m.Called(projectID, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateTestPlan")
	}

	var r0 entities.TestPlan
	var r1 error
	if rf, ok := ret.Get(0).(func(string, entities.CreateTestPlanRequest) (entities.TestPlan, error)); ok {
		return rf(projectID, req)
	}
	if rf, ok := ret.Get(0).(func(string, entities.CreateTestPlanRequest) entities.TestPlan); ok {
		r0 = rf(projectID, req)
	} else {
		r0 = ret.Get(0).(entities.TestPlan)
	}

	if rf, ok := ret.Get(1).(func(string, entities.CreateTestPlanRequest) error); ok {
		r1 = rf(projectID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteTestPlan provides a mock function with given fields: id
func (_m *TestPlanRepository) DeleteTestPlan(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTestPlan")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetTestPlanByID provides a mock function with given fields: id
func (_m *TestPlanRepository) GetTestPlanByID(id string) (entities.TestPlan, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetTestPlanByID")
	}

	var r0 entities.TestPlan
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (entities.TestPlan, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) entities.TestPlan); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(entities.TestPlan)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTestPlansByProject provides a mock function with given fields: projectID
func (_m *TestPlanRepository) GetTestPlansByProject(projectID string) ([]entities.TestPlan, error) {
	ret := _m.Called(projectID)

	if len(ret) == 0 {
		panic("no return value specified for GetTestPlansByProject")
	}

	var r0 []entities.TestPlan
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]entities.TestPlan, error)); ok {
		return rf(projectID)
	}
	if rf, ok := ret.Get(0).(func(string) []entities.TestPlan); ok {
		r0 = rf(projectID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.TestPlan)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(projectID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateTestPlan provides a mock function with given fields: id, req
func (_m *TestPlanRepository) UpdateTestPlan(id string, req entities.CreateTestPlanRequest) (entities.TestPlan, error) {
	ret := _m.Called(id, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTestPlan")
	}

	var r0 entities.TestPlan
	var r1 error
	if rf, ok := ret.Get(0).(func(string, entities.CreateTestPlanRequest) (entities.TestPlan, error)); ok {
		return rf(id, req)
	}
	if rf, ok := ret.Get(0).(func(string, entities.CreateTestPlanRequest) entities.TestPlan); ok {
		r0 = rf(id, req)
	} else {
		r0 = ret.Get(0).(entities.TestPlan)
	}

	if rf, ok := ret.Get(1).(func(string, entities.CreateTestPlanRequest) error); ok {
		r1 = rf(id, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTestPlanRepository creates a new instance of TestPlanRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTestPlanRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *TestPlanRepository {
	mock := &TestPlanRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
