// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	entities "github.com/xurceo/plain-tcms/entities"
)

// TestCaseRepository is an autogenerated mock type for the TestCaseRepository type
type TestCaseRepository struct {
	mock.Mock
}

// CreateTestCase provides a mock function with given fields: projectID, req
func (_m *TestCaseRepository) CreateTestCase(projectID string, req entities.CreateTestCaseRequest) (entities.TestCase, error) {
	ret := _m.Called(projectID, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateTestCase")
	}

	var r0 entities.TestCase
	var r1 error
	if rf, ok := ret.Get(0).(func(string, entities.CreateTestCaseRequest) (entities.TestCase, error)); ok {
		return rf(projectID, req)
	}
	if rf, ok := ret.Get(0).(func(string, entities.CreateTestCaseRequest) entities.TestCase); ok {
		r0 = rf(projectID, req)
	} else {
		r0 = ret.Get(0).(entities.TestCase)
	}

	if rf, ok := ret.Get(1).(func(string, entities.CreateTestCaseRequest) error); ok {
		r1 = rf(projectID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteTestCase provides a mock function with given fields: id
func (_m *TestCaseRepository) DeleteTestCase(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTestCase")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetTestCaseByID provides a mock function with given fields: id
func (_m *TestCaseRepository) GetTestCaseByID(id string) (entities.TestCase, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetTestCaseByID")
	}

	var r0 entities.TestCase
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (entities.TestCase, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) entities.TestCase); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(entities.TestCase)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTestCaseHistory provides a mock function with given fields: testCaseID
func (_m *TestCaseRepository) GetTestCaseHistory(testCaseID string) ([]entities.TestCaseHistory, error) {
	ret := _m.Called(testCaseID)

	if len(ret) == 0 {
		panic("no return value specified for GetTestCaseHistory")
	}

	var r0 []entities.TestCaseHistory
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]entities.TestCaseHistory, error)); ok {
		return rf(testCaseID)
	}
	if rf, ok := ret.Get(0).(func(string) []entities.TestCaseHistory); ok {
		r0 = rf(testCaseID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.TestCaseHistory)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(testCaseID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTestCases provides a mock function with given fields: projectID
func (_m *TestCaseRepository) GetTestCases(projectID string) ([]entities.TestCase, error) {
	ret := _m.Called(projectID)

	if len(ret) == 0 {
		panic("no return value specified for GetTestCases")
	}

	var r0 []entities.TestCase
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]entities.TestCase, error)); ok {
		return rf(projectID)
	}
	if rf, ok := ret.Get(0).(func(string) []entities.TestCase); ok {
		r0 = rf(projectID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.TestCase)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(projectID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateTestCase provides a mock function with given fields: id, req
func (_m *TestCaseRepository) UpdateTestCase(id string, req entities.CreateTestCaseRequest) (entities.TestCase, error) {
	ret := _m.Called(id, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTestCase")
	}

	var r0 entities.TestCase
	var r1 error
	if rf, ok := ret.Get(0).(func(string, entities.CreateTestCaseRequest) (entities.TestCase, error)); ok {
		return rf(id, req)
	}
	if rf, ok := ret.Get(0).(func(string, entities.CreateTestCaseRequest) entities.TestCase); ok {
		r0 = rf(id, req)
	} else {
		r0 = ret.Get(0).(entities.TestCase)
	}

	if rf, ok := ret.Get(1).(func(string, entities.CreateTestCaseRequest) error); ok {
		r1 = rf(id, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTestCaseRepository creates a new instance of TestCaseRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTestCaseRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *TestCaseRepository {
	mock := &TestCaseRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
