// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	entities "github.com/xurceo/plain-tcms/entities"
)

// TestRunRepository is an autogenerated mock type for the TestRunRepository type
type TestRunRepository struct {
	mock.Mock
}

// AddCaseToRun provides a mock function with given fields: runID, testCaseID
func (_m *TestRunRepository) AddCaseToRun(runID string, testCaseID string) error {
	ret := _m.Called(runID, testCaseID)

	if len(ret) == 0 {
		panic("no return value specified for AddCaseToRun")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(runID, testCaseID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AddResultToRun provides a mock function with given fields: runID, req
func (_m *TestRunRepository) AddResultToRun(runID string, req entities.CreateTestResultRequest) (entities.TestResult, error) {
	ret := _m.Called(runID, req)

	if len(ret) == 0 {
		panic("no return value specified for AddResultToRun")
	}

	var r0 entities.TestResult
	var r1 error
	if rf, ok := ret.Get(0).(func(string, entities.CreateTestResultRequest) (entities.TestResult, error)); ok {
		return rf(runID, req)
	}
	if rf, ok := ret.Get(0).(func(string, entities.CreateTestResultRequest) entities.TestResult); ok {
		r0 = rf(runID, req)
	} else {
		r0 = ret.Get(0).(entities.TestResult)
	}

	if rf, ok := ret.Get(1).(func(string, entities.CreateTestResultRequest) error); ok {
		r1 = rf(runID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateTestRun provides a mock function with given fields: projectID, req
func (_m *TestRunRepository) CreateTestRun(projectID string, req entities.CreateTestRunRequest) (entities.TestRun, error) {
	ret := _m.Called(projectID, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateTestRun")
	}

	var r0 entities.TestRun
	var r1 error
	if rf, ok := ret.Get(0).(func(string, entities.CreateTestRunRequest) (entities.TestRun, error)); ok {
		return rf(projectID, req)
	}
	if rf, ok := ret.Get(0).(func(string, entities.CreateTestRunRequest) entities.TestRun); ok {
		r0 = rf(projectID, req)
	} else {
		r0 = ret.Get(0).(entities.TestRun)
	}

	if rf, ok := ret.Get(1).(func(string, entities.CreateTestRunRequest) error); ok {
		r1 = rf(projectID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteTestRun provides a mock function with given fields: id
func (_m *TestRunRepository) DeleteTestRun(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTestRun")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetCasesByRun provides a mock function with given fields: runID
func (_m *TestRunRepository) GetCasesByRun(runID string) ([]entities.TestCase, error) {
	ret := _m.Called(runID)

	if len(ret) == 0 {
		panic("no return value specified for GetCasesByRun")
	}

	var r0 []entities.TestCase
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]entities.TestCase, error)); ok {
		return rf(runID)
	}
	if rf, ok := ret.Get(0).(func(string) []entities.TestCase); ok {
		r0 = rf(runID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.TestCase)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(runID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetResultsByRun provides a mock function with given fields: runID
func (_m *TestRunRepository) GetResultsByRun(runID string) ([]entities.TestResult, error) {
	ret := _m.Called(runID)

	if len(ret) == 0 {
		panic("no return value specified for GetResultsByRun")
	}

	var r0 []entities.TestResult
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]entities.TestResult, error)); ok {
		return rf(runID)
	}
	if rf, ok := ret.Get(0).(func(string) []entities.TestResult); ok {
		r0 = rf(runID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.TestResult)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(runID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTestRunByID provides a mock function with given fields: id
func (_m *TestRunRepository) GetTestRunByID(id string) (entities.TestRun, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetTestRunByID")
	}

	var r0 entities.TestRun
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (entities.TestRun, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) entities.TestRun); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(entities.TestRun)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTestRunsByProject provides a mock function with given fields: projectID
func (_m *TestRunRepository) GetTestRunsByProject(projectID string) ([]entities.TestRun, error) {
	ret := _m.Called(projectID)

	if len(ret) == 0 {
		panic("no return value specified for GetTestRunsByProject")
	}

	var r0 []entities.TestRun
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]entities.TestRun, error)); ok {
		return rf(projectID)
	}
	if rf, ok := ret.Get(0).(func(string) []entities.TestRun); ok {
		r0 = rf(projectID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.TestRun)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(projectID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RemoveCaseFromRun provides a mock function with given fields: runID, testCaseID
func (_m *TestRunRepository) RemoveCaseFromRun(runID string, testCaseID string) error {
	ret := _m.Called(runID, testCaseID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveCaseFromRun")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(runID, testCaseID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateTestRun provides a mock function with given fields: id, req
func (_m *TestRunRepository) UpdateTestRun(id string, req entities.CreateTestRunRequest) (entities.TestRun, error) {
	ret := _m.Called(id, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTestRun")
	}

	var r0 entities.TestRun
	var r1 error
	if rf, ok := ret.Get(0).(func(string, entities.CreateTestRunRequest) (entities.TestRun, error)); ok {
		return rf(id, req)
	}
	if rf, ok := ret.Get(0).(func(string, entities.CreateTestRunRequest) entities.TestRun); ok {
		r0 = rf(id, req)
	} else {
		r0 = ret.Get(0).(entities.TestRun)
	}

	if rf, ok := ret.Get(1).(func(string, entities.CreateTestRunRequest) error); ok {
		r1 = rf(id, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTestRunRepository creates a new instance of TestRunRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTestRunRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *TestRunRepository {
	mock := &TestRunRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
